### ISSUE TITLE
vlan module sets wrong allocation policy for small prefixes

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1361]
https://github.com/ipspace/netlab/blob/cf0c7a89cf6d80109eaa6092f2ac30c7ea7b93fc/netsim/modules/vlan.py#L104

This fails on a "p2p" vlan with a /30 prefix in a topology with enough nodes (high node ids)

Suggested fix is to simply let ```get_prefix_IPAM_policy``` figure this out

**Comment by ipspace** [comment]
That's by design. We never know how many far stretched a VLAN will be and how many hosts will be attached to it. Setting the ID-based allocation is simpler than trying to scan the whole topology to figure out how many devices are attached to a VLAN.

Just set the p2p allocation policy for the VLAN or the pool you're using.

**Comment by jbemmel** [comment]
I get that for larger prefixes, but ```id_based``` likely won't work for a /31 or /30 prefix. Couldn't we add a little more "intelligence" and do ```id_based``` for large enough prefixes, else ```sequential```?

**Comment by ipspace** [comment]
> I get that for larger prefixes, but `id_based` likely won't work for a /31 or /30 prefix. Couldn't we add a little more "intelligence" and do `id_based` for large enough prefixes, else `sequential`?

Can you please explain how are you going to do "sequential" allocation if the same VLAN is used on a dozen of access links? I'm not going to waste my time with this one. Just set the allocation policy for the prefix.

**Comment by jbemmel** [comment]
It's a "p2p" vlan used because the switch in question doesn't support IPs on interfaces directly.

A /30 VLAN is not going to be used on a dozen access links, but I'll concede that this is a corner case and I'll fix it in the topology

**Comment by ipspace** [comment]
> It's a "p2p" vlan used because the switch in question doesn't support IPs on interfaces directly.
> 
> A /30 VLAN is not going to be used on a dozen access links, but I'll concede that this is a corner case and I'll fix it in the topology

Send me the relevant topology snippet and I'll see what could be done.

**Comment by ipspace** [comment]
> It's a "p2p" vlan used because the switch in question doesn't support IPs on interfaces directly.

@jbemmel: I've been thinking about this. It must be a nightmare to specify in the topology file. How about using a plugin that would (after everything else has been done):

* Identify the devices that have to be fixes
* Find all physical layer-3 interfaces
* Assign a unique VLAN to every layer-3 interface
* Create a new VLAN SVI interface from the physical interface data and turn the physical interface into a VLAN access interface

I wanted to write something like that for Arista EOS containers before they implemented MPLS data plane on physical interfaces, so I can write the plugin if you feel that's a viable approach.

**Comment by jbemmel** [comment]
In my case, I'm just trying to reproduce/model an existing configuration on an old Dell switch. It has 1 uplink to another router, where it uses this p2p vlan construct

For me, it would suffice if Netlab could recognize that /30 or /31 subnets only leave room for 2 IPs, and hence any VLANs using that are "p2p" and cannot use the ```id_based``` allocation strategy

Sample topology:
```
nodes: [spine1,spine2,leaf1,leaf2]

module: [vlan]

vlans:
 p2p_vlan:
  prefix: 10.0.0.0/30
 p2p_vlan2:
  prefix: 10.0.0.4/30

links:
- spine1-spine2
- spine1:
  leaf1:
  vlan.trunk: [ p2p_vlan ]
- spine2:
  leaf2:
  vlan.trunk: [ p2p_vlan2 ]
```

Result:
```
jeroen@j:/tmp$ netlab create -p clab -d frr test.yml 
[ERRORS]  Errors found in test.yml
[VALUE]   links: Cannot assign host index 4 in ipv4 from prefix 10.0.0.4/30 to node leaf2
... index out range for address range size!
[FATAL]   Cannot proceed beyond this point due to errors, exiting
```

**Comment by jbemmel** [comment]
Yes I can make it work, but to me this is just something that we needn't bother the average user with. If a user specifies a /30 it's clear that ```id_based``` won't work, but as it is we're forcing them to read up about the notion of an ```allocation``` strategy and how Netlab has certain defaults - it will work for "p2p" links but not "p2p" vlans, because [ you tell me ]

**Comment by ipspace** [comment]
> Yes I can make it work, but to me this is just something that we needn't bother the average user with.

The next time you see an _average user_ doing what you're trying to do here, please let me know.

> If a user specifies a /30 it's clear that `id_based` won't work, but as it is we're forcing them to read up on the notion of an `allocation` strategy and how Netlab has certain defaults - it will work for "p2p" links but not "p2p" vlans, because [ you tell me ]

Because we use "routed vlans" for P2P VLANs (and they work great, check the VRF lite scenarios) and the only reason you're not doing that is because you have an old switch that does not support routed interfaces?

Now, the reason we're not going to do P2P allocation for /30 prefixes is this topology:

```
vlans:
  test:
    prefix:
      ipv4: 10.0.42.0/30
      allocation: p2p
    links: [ s1-h1,s1-h2 ]

nodes:
  s1:
    module: [ vlan ]
    device: eos
  h1:
    device: linux
  h2:
    device: linux
```

H1 and H2 get the same IP address (I told you that would happen two days ago). It's better to force user to read the documentation (or open a discussion) and force netlab to behave in a certain way than to totally confuse them with duplicate IP addresses and no warning.

Finally, yet again I was stupid enough to try to be helpful and waste way too much time I could have spent fixing real problems discussing your personal extremely niche case that you wanted to see as the default netlab behavior to "help the average user". This is my last word on this particular topic.

**Comment by jbemmel** [comment]
This topology would be invalid, because a "p2p" vlan can only apply to 1 link, not 2. It's not just about doing P2P allocation for /30 prefixes, it's about introducing the concept of "p2p vlans". But if you don't want to go there, that's fine

I can check if using a routed VLAN makes any difference

**Comment by jbemmel** [comment]
If I add ```vlan.mode: route``` the prefix specified for each VLAN is ignored, and a different address pool is used (172.16.x.y 'lan' pool)

Let me know if you'd like me to open a separate issue for that
