### ISSUE TITLE
A way to run device commands from command line operating on groups of devices

### ISSUE THREAD

**Issue by DanPartelly** [ipspace/netlab#1392]
During debugging IOL, Ive felt the need to easily run show commands on groups of devices. 
We have netlab connect -s, but it only wants to operate on one device at a time. 

Maybe worthy to add support for running on a group, with an obligatory banner containing the device name to avoid confusion.
What do you guys think ? </div>

**Comment by ipspace** [comment]
Absolutely. Do you want to implement it (with a bit of help) or should I?

**Comment by DanPartelly** [comment]
@ipspace Its high time for me to learn Pyhton.  So Id like to do it myself, if that is ok with you.  It will take longer, but meanwhile you can do other things. Of course, any pointers are appreciated.

**Comment by ipspace** [comment]
How detailed do you want the pointers to be? ;)

**Comment by DanPartelly** [comment]
I ask when I need. You comment when you feel the need. All code will be up for review of course.

**Comment by ipspace** [comment]
> I ask when I need. You comment when you feel the need.

👍 Few things to start with:

- I would reuse the existing host argument to be a node selection expression (host, group, glob). Ensure the parsing help message is relevant.
- We already have the code that takes a node selection expression and returns matching nodes: https://github.com/ipspace/netlab/blob/dev/netsim/cli/report.py#L51
- I would check whether there's a command specified (so it's not a simple remote login) and abort if there's no command (show or otherwise) and the nodeset is larger than one
- Use log.error for all error messages. Ask if the parameters are unclear.

> All code will be up for review of course.

Or it wouldn't get merged ;)

**Comment by DanPartelly** [comment]
I initially thought to introduce a new command  "exec" for this.  netlab exec [-v] [-q] [--dry-run] host command

Advantages:
 - Users may already have shell scripts built against netlab connect  -s , and may not expect those to suddenly start running against groups or globs 
 - Faster to write on command line
 
  Disadvantages:
 - command line namespace pollution. There are quite a few of them already.
 
 Please lemme know your thoughts.

**Comment by DanPartelly** [comment]
Or , use netlab connect but use a separate flag for command execution. Like the ubiquitous "-c" ,  and preserve "-s" exactly like it is now , and make them mutually exclusive.

**Comment by ipspace** [comment]
> I initially thought to introduce a new command "exec" for this. netlab exec [-h] [-q] [--dry-run] host command

That's a really good idea because it's obvious what the command does. **netlab connect** executing a single command specified in the arguments is more of an incident (OK, "organic growth") than good design.

> * Users may already have shell scripts built against netlab connect  -s , and may not expect those to suddenly start running against groups or globs

If the host name is correct, there's no change in behavior. If it's incorrect, they had a problem anyway ;))

> * Faster to write on command line

Use aliases ;))

> Disadvantages:
> 
> * command line namespace pollution. There are quite a few of them already.

Not a problem. Look at virsh.

> Please lemme know your thoughts.

Go with "netlab exec" and we'll deprecate "netlab connect" with additional arguments.

**Comment by ipspace** [comment]
Implemented in #1398
