### ISSUE TITLE
[BUG] Topology containing multiple 'nodes', 'links' or 'vlans' sections results in confusing errors

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1410]
A topology like:
```
nodes:
  n1:
  n2:

....
nodes:
  n3:
  n4:
```
does not generate an error message about having multiple ```nodes``` sections. Instead, you get confusing errors about members in groups being invalid nodes (because only the last section seems to be retained)

Triggered by https://github.com/ipspace/netlab/discussions/1409#discussioncomment-11005163

Perhaps it would be useful to allow for such composite topologies, by merging the sections?

**Comment by ipspace** [comment]
There's not much we can do. This is a YAML parser issue, and it looks like the YAML parser does not get bothered by duplicate keys 🥲 

I know we had PyYAML versus Ruamel discussion a long while ago. In those days, I grudgingly added support for Ruamel because someone might use it, but since Ansible uses PyYAML, I decided to stick with that.

However, based on https://stackoverflow.com/questions/44904290/getting-duplicate-keys-in-yaml-using-python it looks like Ruamel (when used with the new API) triggers the duplicate key error. 

It looks like Box can take arguments that are then passed to PyYAML, so do you want to go down the path of custom safe loader described in the above URL? I wouldn't, but that's just me ;)

**Comment by jbemmel** [comment]
Easy fix in netsim/utils/read.py:
```
# special loader with duplicate key checking
class UniqueKeyLoader(yaml.SafeLoader):
  def construct_mapping(self, node, deep=False):
      mapping = []
      for key_node, value_node in node.value:
          key = self.construct_object(key_node, deep=deep)
          if key in mapping:
            log.fatal(f"Duplicate section in YAML file: {key}") 
          mapping.append(key)
      return super().construct_mapping(node, deep)

...
yaml_data = Box().from_yaml(filename=filename,default_box=True,box_dots=True,default_box_none_transform=False,Loader=UniqueKeyLoader) (2x)
```

Box defaults to Ruamel

**Comment by ipspace** [comment]
> Easy fix in netsim/utils/read.py:

Perfect. Check it with both YAML libraries and submit a PR

> Box defaults to Ruamel

... but we have PyYAML in the requirements so people using Ansible (= eveyone) don't end with two YAML parsers on their system (https://xkcd.com/927/ comes to mind)

**Comment by jbemmel** [comment]
> > Easy fix in netsim/utils/read.py:
> 
> Perfect. Check it with both YAML libraries and submit a PR

This only affects PyYAML: https://github.com/cdgriffith/Box/blob/master/box/converters.py#L237
