### ISSUE TITLE
[BUG] Loopback with IPv6 LLA address leads to crash

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1494]
### Describe the bug

Defining a node with ipv6 lla enabled on its loopback interface (default for several platforms) results in a crash

### To Reproduce
```netlab create testtopo.yml```

### Expected behavior
Topology file specifying ```ipv6: True``` for the loopback interface to enable ipv6 without specifying any specific ip

### Lab topology
```
---
nodes:
 n1:
  loopback:
   ipv6: True
```
### Output
```
Traceback (most recent call last):
  File "/home/jvanbemmel/netlab/netlab", line 14, in <module>
    netsim.cli.lab_commands(__file__)
  File "/home/jvanbemmel/netlab/netsim/cli/__init__.py", line 351, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jvanbemmel/netlab/netsim/cli/create.py", line 93, in run
    output_module.write(topology)
  File "/home/jvanbemmel/netlab/netsim/outputs/ansible.py", line 313, in write
    ansible_inventory(ansible_topology,hostfile,output_format)
  File "/home/jvanbemmel/netlab/netsim/outputs/ansible.py", line 220, in ansible_inventory
    inventory = create(topology)
                ^^^^^^^^^^^^^^^^
  File "/home/jvanbemmel/netlab/netsim/outputs/ansible.py", line 152, in create
    add_host_addresses(topology,inventory)    # Create the 'hosts' dictionary in 'all' group
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jvanbemmel/netlab/netsim/outputs/ansible.py", line 104, in add_host_addresses
    inventory.all.vars.hosts = get_host_addresses(topology)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jvanbemmel/netlab/netsim/outputs/ansible.py", line 85, in get_host_addresses
    lb = str(netaddr.IPNetwork(node.loopback[af]).ip) # Extract IP address from the CIDR prefix
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/netaddr/ip/__init__.py", line 1034, in __init__
    value, prefixlen = parse_ip_network(
                       ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/netaddr/ip/__init__.py", line 925, in parse_ip_network
    raise TypeError('unexpected type %s for addr arg' % type(addr))
TypeError: unexpected type <class 'bool'> for addr arg
```

### Version
dev branch

**Comment by ipspace** [comment]
Thank you! Having LLA on a loopback makes zero sense, we should throw an error as early as feasible. Fortunately, the crash happens very late (when generating Ansible files).

Agree?

**Comment by jbemmel** [comment]
> Thank you! Having LLA on a loopback makes zero sense, we should throw an error as early as feasible. Fortunately, the crash happens very late (when generating Ansible files).
> 
I encountered this while trying to recreate existing network configs using Dell OS10 devices. On those, loopbacks get assigned an ipv6 lla address by default unless you explicitly disable ipv6 using ```no ipv6 enable```

While the network only runs OSPFv2 and those ipv6 addresses probably don't come into play, configs with ipv6 lla on loopbacks exist (and likely are fairly common, given it's what you get by default)

**Comment by ipspace** [comment]
> I am trying to introduce Netlab as a means to implement best practices in network configuration.

That's a marvelous goal, and once you're ready to publish something about the results, please send me a link.

> In some cases, that means changing existing configurations that have evolved over the years. In other cases, it may mean adding a nerd knob to transition from a situation that may be "obsolete" but is supporting critical business applications and is difficult to change over night. I appreciate that a custom local template may be a solution too, to not bother the world with all the technical debt.

That's why we made netlab so extensible. Apart from the core data transformation logic (which can also be tweaked with plugins), everything else can be replaced with your own templates, and you don't even need custom configuration templates. You can, for example, use your own `templates/gateway/dellos10.j2` template.

You can also add directories to search paths (and have search paths modified for the whole project, similar to what I do in the IS-IS labs -- https://github.com/bgplab/isis/blob/master/basic/1-simple-ipv4/topology.yml and https://github.com/bgplab/isis/blob/master/defaults.yml) so you can store shared templates in another Git repo, not just in your home- or system directory.

**Comment by ipspace** [comment]
> I appreciate that, but in the particular case of Dell OS10 that doesn't work with the current implementation: The quirk logic rules out any chance of using OSPF on VLAN interfaces, regardless of the templates used

THAT is a huge issue. You should have started with it instead of trying to persuade us to implement legacy stuff.

> That limitation is a consequence of the design choice to use virtual networks - not a fundamental limitation of the device. We could move the check to the template

Because it's so much fun to figure out why an Ansible playbook crashes amid all the nonsense Ansible generates? 😜

Ansible verbal diarrhea is one of the major reasons I implemented quirks.

> - OR (as I put in that PR) make it conditional on some Boolean flag

No, you did not put that in that PR. What you did was modify the standard configuration template and a bunch of other things trying to squeeze a legacy way of doing things into netlab core. What we have to do is to make quirks easy to disable.

**Comment by jbemmel** [comment]
> 
> No, you did not put that in that PR. What you did was modify the standard configuration template and a bunch of other things trying to squeeze a legacy way of doing things into netlab core. What we have to do is to make quirks easy to disable.

I was talking about https://github.com/ipspace/netlab/pull/1484/files:
* Modify the Dell OS10 vlan template: ```{% if vlans is defined and use_virtual_networks|default(True) %}```
* Make the device quirk conditional on use_virtual_networks
* Make it possible to use different SVI interface names based on topology settings

**Comment by ipspace** [comment]
> I was talking about https://github.com/ipspace/netlab/pull/1484/files:

Thank you for reiterating what I just said. You also forgot to mention that you had to change the way interface names are generated because you needed access to a device feature flag, not to mention making the `svi_interface_name` parameter a nightmare to read.

**Comment by jbemmel** [comment]
> 
> Thank you for reiterating what I just said. You also forgot to mention that you had to change the way interface names are generated because you needed access to a device feature flag, not to mention making the `svi_interface_name` parameter a nightmare to read.

That's the "Make it possible to use a different SVI interface naming convention based on topology settings" part, and I did state upon submission "One could see this as a bit of a hack - open to less hacky alternatives if any" anticipating your disapproval.

So "hacky" perhaps, but not "trying to squeeze a legacy way of doing things into netlab core" (at least not in this PR ;)

**Comment by ipspace** [comment]
> And regarding the "You should have started with that" - here's what I put in that PR:

From where I'm sitting, there's a bit of a difference between submitting a PR with "I want to change a working configuration template because my old software doesn't support that, and a way an interface is named, and how we create interface names" and an "I know I should use custom templates, and I tried that, but the quirks won't allow me to do so" issue.

But maybe that's just because I'm not a native English speaker and can't understand the nuances.

Anyway, one of these days I might be able to learn not to waste time in pointless discussions, but looks like I'm not there yet.
