### ISSUE TITLE
[BUG] Unable to unset global MTU setting

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1603]
For testing purposes my topology unsets the MTU:
```
defaults.devices.dellos10:
 clab.mtu: # No value
```

This causes Netlab to generate YAML with ```mtu: null``` entries, due to https://github.com/ipspace/netlab/blob/2cffc6e496b08a3f3609dd070066ae2c98584ef7/netsim/augment/links.py#L327

**Comment by ipspace** [comment]
There is no way to "unset" the defaults, and setting a thing to None is not the same as unsetting it.

Write a plugin that will remove the default setting before the link function is called.

**Comment by ipspace** [comment]
* f2eadec1e2129353e268ae535fdf8b74800e9452 might do what you want. It was a pretty harmless change, so OK.
* Don't ever mention 'unsetting the defaults'. If you want to do that, write a plugin.
* I wanted to add a sanity check of default values copied into node values but decided not to do it.
* I added a warning that the defaults are not sanity-checked and will point you to that warning every time you'll complain about the defaults.

Finally: you said you "wanted to do some testing". You could have set the MTU to a higher value and move on instead of wasting time with your very special way of doing things.

**Comment by jbemmel** [comment]
> Finally: you said you "wanted to do some testing". You could have set the MTU to a higher value and move on instead of wasting time with your very special way of doing things.

Specifically, I am testing differences between Dell OS9 and OS10 which have different platform default MTU settings for different releases. Configuring a specific value is different from not configuring a MTU value

Thank you for making the change - harmless as it may be, it makes the difference between being able to test what I need to test, or not
