### ISSUE TITLE
[BUG] Error not triggered if vlan.mixed_trunk set to false?

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#1708]
I am in the process of refactoring all the big mess related to the different ways of handling VLANs for the different Juniper device models.

I was expecting that removing `features.vlan.mixed_trunk` (or setting it to false) for a device should have triggered a "fatal error" for tests *62-vlan-mixed-trunk.yml* *63-vlan-mixed-native.yml* but, instead, `netlab up` seems happy and continues with that (triggering a device error during ansible configuration later on).

**Comment by jbemmel** [comment]
See https://github.com/jbemmel/netlab/blob/5ddb8fde8e7ef9c93c3cfe6571682d2574d16ea4/netsim/modules/vlan.py#L1079

There is no error in 2 cases:
1. Device supports mixed_trunk
2. Device uses subinterfaces to implement VLANs

Perhaps you have case #2?

**Comment by ipspace** [comment]
@jbemmel is right. The "mixed_trunk" is checked only for layer-3 switches, not for routers. Routers are assumed to have subinterface, and it's assumed the subinterface can be bridged together (think Cisco IOS bridge-groups) or be routed interfaces.

See https://netlab.tools/dev/config/vlan/ for more details. The three blog posts listed in that document might also be helpful.

If it turns out Junos does not conform to either of those models (I wouldn't be surprised ;)), we might have to implement a device quirk.

**Comment by ssasso** [comment]
In my case, it's for a "l3-switch" kind of device...

**Comment by ipspace** [comment]
> In my case, it's for a "l3-switch" kind of device... (vjunos-switch)

OK, so you took the existing vjunos-switch settings and "netlab create" survived 62-vlan-mixed-trunk.yml with `features.vlan.mixed_trunk` set to False? That seems like something I have to fix 🤷‍♂️ Will figure it out.

**Comment by ssasso** [comment]
Correct.

When I created the device file I don't know why I put that to true.
It's not working now, and I suspect it was not working also in the past.

So as part of refactoring I'm also re running all the vlan testing, and I noticed that removing it (or setting that to false) does not trigger any error.

**Comment by ipspace** [comment]
Should be fixed. Please let me know if you experience any other challenges.

**Comment by ssasso** [comment]
works. thanks a lot! :)
