### ISSUE TITLE
Use bgp.local_as and bgp.activate functionality for EVPN IBGP-over-EBGP on VyOS and Dell OS10

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#363]
We will eventually get to the point where someone will say "it would be great to have EBGP local-as functionality" outside of the "let's create job security by running IBGP over EBGP" EVPN use case.

The functionality is almost there (in the current ebgp-local_as.py plugin), but would need to be generalized:

* I would rename the plugin to **ebgp.local_as** to keep the **protocol.feature** naming convention
* It would have to be migrated into a directory within `extra` directory to enable platform-specific configuration templates
* It should use **bgp.local_as** and not **something.underlay_as** attribute as we're no longer solving just the EVPN use case.
* **local-as** configuration should be moved into the plugin custom configuration template, right now I have a feeling it's all over the place

That would result in a consistent and easy-to-extend (platform-wise) **local-as** functionality that's independent of EVPN.

Next, we could implement an EVPN plugin (for example, **evpn.ibgp_over_ebgp**) that would:

* Use the **evpn.underlay_as** attribute to signal the IBGP-over-EBGP design
* Copy **evpn.underlay_as** to **bgp.local_as** on all interfaces (ideally node-link-attachment data) with IBGP peers. We have to find the perfect plugin hook to do that -- it has to be done after the module attributes are copied into nodes, but before the interfaces are created or before **ebgp.local_as** plugin modifies the list of neighbors.
* Use custom configuration templates in **evpn.ibgp_over_ebgp** plugin to disable IPv4/IPv6 AF on IBGP sessions when **evpn.underlay_as** is present.

Have I missed something? Ready to go for it @jbemmel @ssasso?

**Comment by ssasso** [comment]
_You can count on me!... but after September 20.
I'll be abroad for a pause for a couple of weeks._

**Comment by ipspace** [comment]
> You can count on me!...

👍

> but after September 20. I'll be abroad for a pause for a couple of weeks.

There's no rush. Enjoy the vacations (or whatever it is).

**Comment by jbemmel** [comment]
We could do this, but perhaps it would be better to integrate local_as logic with the core bgp module?

See e.g. https://github.com/ipspace/netlab/blob/dev/netsim/modules/bgp.py#L246 - local_as could (theoretically) turn ebgp into ibgp sessions, and create additional ebgp sessions. While the plugin could iterate over existing neighbor structures and correct them, I think it would be easier to add 1 line of logic accounting for 'local_as'

We could then rename the plugin to ibgp_over_ebgp and keep the underlay_as logic, inserting local_as attributes as needed. The device templates can then apply it - regardless where local_as comes from. 

Alternatively, we could use 'local_as' at node level instead of 'underlay_as', and remove the plugin altogether

**Comment by jbemmel** [comment]
Just to be clear - you're suggesting to stop using 'bgp.underlay_as' and use bgp.local_as instead?

But keep the plugin to create the ebgp sessions? Or move that to the BGP main module too?

**Comment by ipspace** [comment]
> Just to be clear - you're suggesting to stop using 'bgp.underlay_as' and use bgp.local_as instead?

Yes.

> But keep the plugin to create the ebgp sessions? Or move that to the BGP main module too?

No. The main BGP module already does that ;) The only bit missing to get rid of the plugin is #366

**Comment by ipspace** [comment]
@jbemmel I have a feeling you already fixed this, in which case I'll immediately remove Nokia from the issue title ;)
