### ISSUE TITLE
IBGP local-as sessions (if supported) on Dell OS10, VyOS

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#368]
A quick glance at the recent code changes shows a new 'localas_ibgp' neighbor type. It is currently only referenced within the bgp module, but it can be present in the input for templates.

This breaks logic like https://github.com/ipspace/netlab/blob/dev/netsim/ansible/templates/bgp/eos.macro.j2#L11 which assumes there are only 'ibgp' or 'ebgp' values.

This may be a work in progress - just documenting what I noticed

**Comment by ipspace** [comment]
You're absolutely right. Unfortunately, there are vendors (at the very minimum Cisco IOS XE) who found it expedient to implement an abomination where the use of **local-as** can turn what should be an EBGP session into an IBGP session.

We can't handle that as an IBGP session because we shall not set the **neighbor update-source**. We can't handle it as an EBGP session as we might have to set **neighbor route-reflector-client**.

In any case, I will add a "device feature" check to make it disabled by default, expecting that whoever will set that flag in the **topology-defaults** will also do the right thing in the device configuration templates. Any takers (cc @ssasso)?

**Comment by ipspace** [comment]
BTW, there might be another session type coming in near future: "vrf_ibgp"

@ssasso has mentioned it a long while ago, and now that I'm doing all this crazy stuff, I could implement that one as well.

In any case, I would suggest restructuring templates that don't use peer groups to follow this logic:

* if session_type == 'ibgp' ==> set update source to loopback
* if session_type contains 'ibgp' ==> do the other IBGP stuff like route reflector clients, IBGP community setup...
* otherwise we're dealing with ebgp session.

**Comment by ipspace** [comment]
I'm disgusted. Arista EOS also supports this monstrosity. Implemented in 957489254b2a1e6dcc8bef8a728c48b05003e108

**Comment by jbemmel** [comment]
I can see why we’d need (subtly) different types, agree that a device feature flag (bgp.local_as?) could be added to signal support in templates

**Comment by ipspace** [comment]
We need some way to figure out what needs to be configured (in particular, 'update source') in the templates. We could either check the session type or session type and additional flags, which could be **local_as** or **vrf** or who knows what else the vendors will throw at us.

Session type won't be set to 'localas_ibgp' unless the device feature flag indicates that's supported, so no worries -- it won't appear if your device doesn't support that (no device should, but that's a different story).

So, what's the problem?

**Comment by ipspace** [comment]
Here's another reason why it might be better to use **localas_ibgp** instead of **ibgp** and **local_as**:

* You will have to handle **localas_ibgp** sessions differently from the **ibgp** sessions -- the source address of the TCP session is different (directly connected versus loopback), and the next-hop-self handling might be different (I had to use **next-hop-peer** on Arista EOS).
* If you use BGP templates (or neighbor policy or whatever it's called), you will have to put IBGP peers created through local-as hacks in a different group anyway because they are really a mix of IBGP and EBGP parameters.
* Use **localas_ibgp** type directly translates into yet-another group name, otherwise you'd have to calculate group names on the fly.

I know that's a minor detail, but it might make some templates a tiny bit cleaner (one of these days I have to rewrite Arista and Cisco templates to use BGP policies)

**Comment by jbemmel** [comment]
For BGP unnumbered on SR Linux I sometimes use 'bgp-unnumbered-{local_as}' as the peer group name, since the 'local_as' parameter can only be set in the group, not per interface neighbor

I have no problem here

**Comment by ipspace** [comment]
> For BGP unnumbered on SR Linux I sometimes use 'bgp-unnumbered-{local_as}' as the peer group name, since the 'local_as' parameter can only be set in the group, not per interface neighbor

😱🤦‍♂️

Would it help to have the groups precomputed, for example based on a configurable set of grouping attributes (type/unnumbered/local-as)?

**Comment by jbemmel** [comment]
For this platform specific issue, I think handling it in the templates is more appropriate. 

However, I would like to see a generic BGP peer group mechanism for consistency across platforms - I think it's common enough, and would lead to more readable / comparable configs

**Comment by ipspace** [comment]
> However, I would like to see a generic BGP peer group mechanism for consistency across platforms - I think it's common enough, and would lead to more readable / comparable configs

Sounds like a fun idea. Will do ;)

**Comment by jbemmel** [comment]
bgp.local_as for srlinux is in https://github.com/ipspace/netlab/pull/371

**Comment by ipspace** [comment]
@jbemmel: Just FYI: in the commit 79c2d566c7979cc425399e741e905bd5d68db251 you changed the FRR feature flags to indicate FRR supports IBGP local-as.  The FRR documentation has a pretty clear opinion about that:

> This command is only allowed for eBGP peers.

You also indicated FRR supports **vrf_local_as** without implementing it.

I fixed both in 53725e4eaea4d219e9a16e5ddd5f0868b25707a0

**Comment by ipspace** [comment]
@ssasso Could you please check whether Dell OS10 or VyOS support IBGP local-as sessions (local-as equal to remote-as) so we can close this one if the answer is **no**, which is suspect is the case for VyOS as it seems to be riding on top of FRR.

**Comment by jbemmel** [comment]
I was feeling generous ;)

**Comment by ipspace** [comment]
> I was feeling generous ;)

I'm sure the first user stumbling upon your generosity would be as delighted as I was 🤨

> For SR Linux I structured the templates in a way that local-as gets configured in 1 place for both cases, hence the mix-up

It's not the question of whether the configuration is correct (it is), but whether it works (it does not), and whether you checked it before saying it works.

**Comment by ssasso** [comment]
> @ssasso Could you please check whether Dell OS10 or VyOS support IBGP local-as sessions (local-as equal to remote-as) so we can close this one if the answer is **no**, which is suspect is the case for VyOS as it seems to be riding on top of FRR.

On *VyOS* is, **no**,

as well on *Dell OS10*:

![image](https://user-images.githubusercontent.com/852093/192251922-5e2a0257-3231-4706-a59e-8b492c8defcd.png)

Closing this.
