### ISSUE TITLE
Module requirement check per node

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#399]
https://github.com/ipspace/netlab/blob/af60a885f35a87bfb7cdbdc4d3ffbdc43c2ac79a/netsim/modules/__init__.py#L413

In case of vxlan, the vlan module needs to be applied to the device where the vxlan module is applied. It is not sufficient to have 'vlan' in the global module list

**Comment by jbemmel** [comment]
A related comment regarding https://github.com/ipspace/netlab/blob/dev/netsim/modules/__init__.py#L445

The sort order should consider device specific 'require' lists too

**Comment by ipspace** [comment]
> In case of vxlan, the vlan module needs to be applied to the device where the vxlan module is applied. It is not sufficient to have 'vlan' in the global module list

I tentatively agree... Have no idea (at the moment) why I added the "global modules" check there. Have to do a few tests first, and it's too early for that...

**Comment by ipspace** [comment]
> A related comment regarding https://github.com/ipspace/netlab/blob/dev/netsim/modules/__init__.py#L445
> 
> The sort order should consider device specific 'require' lists too

Nope. Just because VXLAN needs EVPN on Nokia SR Linux does not mean that EVPN transformation should be done before VXLAN transformation (it should NOT be), or that EVPN should be configured before VXLAN (it should NOT be on most other platforms).

Also, the transformation order (the order in which module hooks are called) is global and cannot be changed for individual nodes.

**Comment by jbemmel** [comment]
The case in point was adding VXLAN and VRF support for frr (i.e. both l2 and l3).

When l3 vxlan is used, vrfs need to be created before adding the l3 vni interfaces to them. I tried adding 'requires' at the device level - though suboptimal, as one can build l2-only vxlan setups - but that doesn't (currently) change the configuration order. 

Are you ok with adding 'config_after: [ vrf ]' for vxlan globally instead?

**Comment by ipspace** [comment]
> The case in point was adding VXLAN and VRF support for frr (i.e. both l2 and l3).

Why don't you use Cumulus container?

Also, FRR is a data-plane-only container, and it might be fun to get VLANs, VRFs and VXLAN to work. I don't think it makes sense to discuss anything until you have it working (outside of netlab).

> When l3 vxlan is used, vrfs need to be created before adding the l3 vni interfaces to them. I tried adding 'requires' at the device level - though suboptimal, as one can build l2-only vxlan setups - but that doesn't (currently) change the configuration order.

We all had that problem. There's a circular dependency between VLANs, VRFs, and interfaces on most platforms. That's why we're configuring VRFs and VLANs in the initial configuration phase, and only adding extra stuff like BGP route redistribution in VRF configuration module.

> Are you ok with adding 'config_after: [ vrf ]' for vxlan globally instead?

I don't see how that could hurt us. Right now they are independent, and stuff works.
