### ISSUE TITLE
Transformation hooks should also be called in module dependency order

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#402]
At https://github.com/ipspace/netlab/blob/af60a885f35a87bfb7cdbdc4d3ffbdc43c2ac79a/netsim/modules/__init__.py#L84 modules are sorted for Ansible playbooks to be run in order, but there are cases where transformation by a module depends on another module too.

Would suggest to move the sorting up, to before hook processing

**Comment by ipspace** [comment]
What you're looking for is most probably **transform_after** module attribute in topology defaults.

**Comment by ipspace** [comment]
> Would it hurt to order the modules before calling transformation hooks - honoring both 'transform_after' and 'configure_after'?

If life would be that simple we wouldn't have two attributes. I remember having to add **transform_after** because there was a pair of modules (can't remember what they were) where we had to transform them in one order, but configure them in another order.

> Main reason is consistency of execution and reproducibility of issues: Currently, the transformation order is partly dependent on the order in which the user lists the modules in their topology.

If two modules don't have dependencies, that doesn't matter. If they have a dependency we did not consider, then we should fix **config_after** or **transform_after** lists.

> Unless we define a complete ordering by adding (arbitrary) transform_after constraints, runs will vary

We had that discussion before, and (IIRC) agreed it doesn't matter. Also, the whole thing is becoming a spaghetti blob of complexity -- that's why I'm always asking for full topology, and why we have so many integration test cases.
