### ISSUE TITLE
Creating virtual interfaces for VXLAN-enabled VLANs

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#403]
Similar to 'create_svi_interfaces' in vlan.py, I think we could use 'create_vxlan_interfaces' in vxlan.py

For one, the vrf module currently gets removed if there are no interfaces associated with any vrf. A VXLAN VTEP node can have vrfs that are purely reachable via VXLAN

Happy to contribute if you're ok with this

**Comment by ipspace** [comment]
We had this discussion already (potentially under a different disguise).

Give me an example. Most platforms need an interface to be able to process packets.

**Comment by jbemmel** [comment]
Related: https://github.com/ipspace/netlab/issues/316

Context is using the vrf module also for L3 vxlan vrfs (I realize it's currently IP VPN focused)

On a FRR node this involves:
* Creating a VRF (separate route table)
* Create a bridge and vxlan interface for the l3 vni, associate with the VRF
* Create a bridge and vxlan interface for the l2 vni, associate with the VRF
* Announce the VNIs through EVPN

There is a regular interface in the default VRF, and a VTEP loopback. However, in the current data model, none of these interfaces are associated with the overlay VRF - hence it gets removed

One option (currently implemented locally) is to not remove the vrf module even when there are no explicit interfaces using vrfs (count==0), when a given node uses the vxlan module.

Another - suggested here - is to model vxlan interfaces just like we model svi interfaces and vlan_member interfaces. This logic is currently hidden in some templates, but could be added. Platforms that don't need/use these interfaces would not include the feature flag (naming convention for the interface)

**Comment by ipspace** [comment]
> Context is using the vrf module also for L3 vxlan vrfs (I realize it's currently IP VPN focused). On a FRR node this involves:

As I told you somewhere else: when you get data-plane L3 VXLAN VRF working in FRR (preferably on vanilla Ubuntu install) please let me know, then we'll look at the configuration, then we might decide what to do.

> One option (currently implemented locally) is to not remove the vrf module even when there are no explicit interfaces using vrfs (count==0), when a given node uses the vxlan module.

I'm perfectly OK with a device feature flag saying "never remove the VRF module" if that's what you're looking for. Then you can create whatever interfaces you wish based on **vrfidx**.

**Comment by jbemmel** [comment]
I got data-plane L3 VXLAN with vrfs working between frr and srlinux; see https://github.com/FRRouting/frr/issues/6785 for a rough outline.

PRs submitted, only need to put IP manually on the frr vxlan bridge interface right now (modeling to be discussed)

Working on an example topology for netsim-examples

**Comment by ipspace** [comment]
The FRRouting example would work perfectly well with existing data model and would require no changes whatsoever:

* The link to **host1** would be an Ethernet interface. The example uses another namespace because he's simulating a host on the same Linux box.
* That link would be on an access VLAN, which would automatically create the bridge interface.
* The VLAN would belong to a VRF, which would automatically create the VRF, and put the bridge interface in the VRF.
* The access VLAN would automatically result in VXLAN VNI
* You could create the transit VXLAN segment from the evpn.transit_vni, and it looks like it doesn't need an IP address.

Alternative, if you want a pure L3 solution:

* Put the link to **host1** into a VRF. That would create the VRF interface and put the physical interface into it.
* Add **evpn.transit_vni** to the VRF. That would create the transit VXLAN interface.

So, where's your problem?

**Comment by ipspace** [comment]
I guess we've solved this, if not please reopen.
