### ISSUE TITLE
Linux deploy commands depend on Python being installed

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#647]
https://github.com/ipspace/netlab/blob/a55a60d650915886c4d92bef0dc9fd127ef28da0/netsim/ansible/tasks/deploy-config/linux.yml#L1

Using Netlab with linux container images that do not contain Python binaries currently fails. 
In contrast, alternatives like the Ansible 'script' action do not depend on Python (though a quick test didn't work for me)

**Comment by ipspace** [comment]
> In contrast, alternatives like the Ansible 'script' action do not depend on Python (though a quick test didn't work for me)

... because your information is wrong ;) The only Python-less Ansible module that I'm aware of is **raw**. However we'd have to execute a convoluted sequence of modules to avoid Python on remote host:

* Generate script file locally
* Use **command** module (or similar) with **delegate_to** localhost to run SCP (which gets interestingly complicated the moment someone starts using SSH parameters) to copy the script file to the device
* Use **raw** module to execute the script on the device

We're not going to do it just because some containers don't include Python... and the whole conundrum applies only to containers anyway.

If we get a feasible idea in #648 then we'll implement it

**Comment by jbemmel** [comment]
See https://docs.ansible.com/ansible/latest/collections/ansible/builtin/script_module.html

"This module does not require python on the remote system, much like the [ansible.builtin.raw](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/raw_module.html#ansible-collections-ansible-builtin-raw-module) module."

However, ```script``` appears to be broken in combination with ```connection: docker```. The 'PUT' command fails to use docker cp

**Comment by ipspace** [comment]
And so I learn something new every day ;) Thank you!

Still, it can transfer and execute a script, not a template, so we'd have to go for multiple steps anyway (**script** module covers #2 and #3 in my list).

Finally, there's no guarantee that whatever container you want to run has the Linux CLI commands used by netlab configuration scripts.
