### ISSUE TITLE
Make loopback interfaces passive by default?

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#776]
https://github.com/ipspace/netlab/blob/8af663e2668aab0863662f56ace8dc88d500abea/netsim/modules/_routing.py#L99

'stub' interfaces are configured as 'passive', but loopback interfaces are not

```
intf[proto].passive = intf.type in ["stub","loopback"] or ...
```

**Comment by ipspace** [comment]
Interesting. Is there a reason you're concerned with this? In the last 30 years I never had to think about passive loopback interfaces.

**Comment by jbemmel** [comment]
It's just for consistency - some of the templates configure the system interface as passive (e.g. https://github.com/ipspace/netlab/blob/dev/netsim/ansible/templates/ospf/vyos.ospfv2.j2#L9) but additional loopbacks become active (non-passive) by default

Adding 'passive: true' for the system loopback is a habit of mine, I realized it's superfluous (hence not a PR but an "issue"...)

**Comment by ipspace** [comment]
> It's just for consistency - some of the templates configure the system interface as passive

@ssasso: Is there any good reason to have loopback as passive on VyOS?
@jbemmel: You can also make the primary loopback active to stay consistent 😉

> but additional loopbacks become active (non-passive) by default

The only difference between a passive and an active OSPF interface is whether the hello protocol is running on it, and it really doesn't matter on loopback.

Based on all the stupidities and gotchas I've seen since we started this project, I would also not be surprised if there are platforms where you cannot configure passive interface on loopbacks.

So I'd say "leave them as they are right now" and if someone insists on making loopbacks passive they could do it in the device configuration template.
